import polars as pl
from pyarrow import string, struct, list_, float64, int32

metrics_common_schema = {
    "average_time_spent": float64(),
    "bouncerate": float64(),
    "dyf_no": int32(),
    "dyf_submit": int32(),
    "dyf_yes": int32(),
    "gsc_searchterms": list_(
        struct(
            {
                "clicks": int32(),
                "ctr": float64(),
                "impressions": int32(),
                "position": float64(),
                "term": string(),
            }.items()
        )
    ),
    "gsc_total_clicks": int32(),
    "gsc_total_ctr": float64(),
    "gsc_total_impressions": int32(),
    "gsc_total_position": float64(),
    "nav_menu_initiated": int32(),
    "views": int32(),
    "visitors": int32(),
    "visits": int32(),
    "visits_device_desktop": int32(),
    "visits_device_mobile": int32(),
    "visits_device_other": int32(),
    "visits_device_tablet": int32(),
    "visits_geo_ab": int32(),
    "visits_geo_bc": int32(),
    "visits_geo_mb": int32(),
    "visits_geo_nb": int32(),
    "visits_geo_nl": int32(),
    "visits_geo_ns": int32(),
    "visits_geo_nt": int32(),
    "visits_geo_nu": int32(),
    "visits_geo_on": int32(),
    "visits_geo_outside_canada": int32(),
    "visits_geo_pe": int32(),
    "visits_geo_qc": int32(),
    "visits_geo_sk": int32(),
    "visits_geo_us": int32(),
    "visits_geo_yt": int32(),
    "visits_referrer_other": int32(),
    "visits_referrer_searchengine": int32(),
    "visits_referrer_social": int32(),
    "visits_referrer_typed_bookmarked": int32(),
    "visits_referrer_convo_ai": int32(),
}

metrics_common_top_level_aggregations_expr = [
    pl.col("average_time_spent").mean().round_sig_figs(5),
    pl.col("bouncerate").mean().round_sig_figs(5),
    pl.col("dyf_no").sum(),
    pl.col("dyf_yes").sum(),
    pl.col("dyf_submit").sum(),
    pl.col("gsc_total_clicks").sum(),
    pl.col("gsc_total_impressions").sum(),
    pl.col("gsc_total_position").mean().round_sig_figs(5),
    pl.col("gsc_total_ctr").mean().round_sig_figs(5),
    pl.col("nav_menu_initiated").sum(),
    pl.col("views").sum(),
    pl.col("visits").sum(),
    pl.col("visitors").sum(),
    pl.col("visits_geo_ab").sum(),
    pl.col("visits_geo_bc").sum(),
    pl.col("visits_geo_mb").sum(),
    pl.col("visits_geo_nb").sum(),
    pl.col("visits_geo_nl").sum(),
    pl.col("visits_geo_ns").sum(),
    pl.col("visits_geo_nt").sum(),
    pl.col("visits_geo_nu").sum(),
    pl.col("visits_geo_on").sum(),
    pl.col("visits_geo_outside_canada").sum(),
    pl.col("visits_geo_pe").sum(),
    pl.col("visits_geo_qc").sum(),
    pl.col("visits_geo_sk").sum(),
    pl.col("visits_geo_us").sum(),
    pl.col("visits_geo_yt").sum(),
    pl.col("visits_referrer_other").sum(),
    pl.col("visits_referrer_searchengine").sum(),
    pl.col("visits_referrer_social").sum(),
    pl.col("visits_referrer_typed_bookmarked").sum(),
    pl.col("visits_referrer_convo_ai").sum(),
    pl.col("visits_device_other").sum(),
    pl.col("visits_device_desktop").sum(),
    pl.col("visits_device_mobile").sum(),
    pl.col("visits_device_tablet").sum(),
]
