export const facts: string[] = [
  "During your lifetime, you'll eat about 60,000 pounds of food, that's the weight of about 6 elephants.",
  'In Switzerland, it is illegal to own just one guinea pig because they are social animals and need the company of their own kind.',
  'A flock of crows is known as a murder.',
  'So far, two diseases have successfully been eradicated: smallpox and rinderpest.',
  'Bananas are curved because they grow towards the sun.',
  'During your lifetime, you will produce enough saliva to fill two swimming pools.',
  'An eagle can kill a young deer and fly away with it.',
  'Heart attacks are more likely to happen on a Monday.',
  'Tennis players are not allowed to swear when they are playing in Wimbledon.',
  'Recycling one glass jar saves enough energy to watch television for 3 hours.',
  "After the premiere of '16 and Pregnant,' teen pregnancy rates dropped.",
  'Approximately 10-20% of U.S. power outages are caused by squirrels.',
  'Facebook, Instagram, and Twitter are all banned in China.',
  'Honeybees can recognize human faces.',
  "Sea otters hold hands when they sleep so they don't drift away from each other.",
  'A small child could swim through the veins of a blue whale.',
  "Hewlett-Packard's (also known as HP) name was decided in a coin toss in 1939.",
  'There is a total of 1,665 steps in the Eiffel Tower.',
  "In 2011, more than 1 in 3 divorce filings in the U.S. contained the word 'Facebook.'",
  'Honeybees can get drunk on fermented tree sap.',
  'Tears contain a natural pain killer which reduces pain and improves your mood.',
  'Millions of birds a year die from smashing into windows in the U.S. alone.',
  'In total, there are 205 bones in the skeleton of a horse.',
  'Each year there are more than 40,000 toilet-related injuries in the United States.',
  'As of October 2018, there are more than 1.9 billion websites on the Internet.',
  'The first-ever email was sent in 1971.',
  'Google receives over 63,000 searches per second on any given day.',
  'Canada is the second-largest country in the world by land area.',
  'Canada has the longest coastline of any country in the world.',
  'The national animal of Canada is the beaver.',
  "Canada is home to more lakes than the rest of the world's lakes combined.",
  "The name 'Canada' originates from the Iroquoian word 'kanata,' meaning village or settlement.",
  'The Canadian province of Alberta has one of the largest reserves of oil sands in the world.',
  'Basketball was invented by Canadian James Naismith in 1891.',
  'The Royal Canadian Mounted Police (RCMP) is a famous symbol of Canada, known for their red serge uniforms.',
  "Canada's national flag, featuring a red maple leaf, was officially adopted on February 15, 1965.",
  "Canada is one of the world's top education performers and among the top countries in spending per capita on public postsecondary education.",
];
