export const facts: string[] = [
  'fun-fact-01',
  'fun-fact-02',
  'fun-fact-03',
  'fun-fact-04',
  'fun-fact-05',
  'fun-fact-06',
  'fun-fact-07',
  'fun-fact-08',
  'fun-fact-09',
  'fun-fact-10',
  'fun-fact-11',
  'fun-fact-12',
  'fun-fact-13',
  'fun-fact-14',
  'fun-fact-15',
  'fun-fact-16',
  'fun-fact-17',
  'fun-fact-18',
  'fun-fact-19',
  'fun-fact-20',
];
// export const facts: string[] = [
//   "During your lifetime, you'll eat about 60,000 pounds of food, that's the weight of about 6 elephants.",
//   'In Switzerland, it is illegal to own just one guinea pig because they are social animals and need the company of their own kind.',
//   'Bananas are curved because they grow towards the sun.',
//   'Tennis players are not allowed to swear when they are playing in Wimbledon.',
//   'Recycling one glass jar saves enough energy to watch television for 3 hours.',
//   'Honeybees can recognize human faces.',
//   "Sea otters hold hands when they sleep so they don't drift away from each other.",
//   'A small child could swim through the veins of a blue whale.',
//   'There is a total of 1,665 steps in the Eiffel Tower.',
//   'Honeybees can get drunk on fermented tree sap.',
//   'Tears contain a natural pain killer which reduces pain and improves your mood.',
//   'In total, there are 205 bones in the skeleton of a horse.',
//   'As of 2023, there are more than 1.13 billion websites on the Internet.',
//   'The first-ever website was published on August 6, 1991, by British physicist Tim Berners-Lee.',
//   'The first-ever website is still online.',
//   'The first-ever email was sent in 1971.',
//   'Google receives over 63,000 searches per second on any given day.',
//   'Canada is the second-largest country in the world by land area.',
//   'Canada has the longest coastline of any country in the world.',
//   'The national animal of Canada is the beaver.',
//   "Canada is home to more lakes than the rest of the world's lakes combined.",
//   "The name 'Canada' originates from the Iroquoian word 'kanata,' meaning village or settlement.",
//   'Basketball was invented by Canadian James Naismith in 1891.',
//   "Canada's national flag, featuring a red maple leaf, was officially adopted on February 15, 1965.",
//   "Canada is one of the world's top education performers and among the top countries in spending per capita on public postsecondary education.",
// ];
