export const topLevelMetricsGrouping = {
  average_time_spent: { $avg: '$average_time_spent' },
  bouncerate: { $avg: '$bouncerate' },
  dyf_no: { $sum: '$dyf_no' },
  dyf_yes: { $sum: '$dyf_yes' },
  dyf_submit: { $sum: '$dyf_submit' },
  gsc_total_clicks: { $sum: '$gsc_total_clicks' },
  gsc_total_impressions: { $sum: '$gsc_total_impressions' },
  gsc_total_position: { $avg: '$gsc_total_position' },
  gsc_total_ctr: { $avg: '$gsc_total_ctr' },
  nav_menu_initiated: { $sum: '$nav_menu_initiated' },
  views: { $sum: '$views' },
  visits: { $sum: '$visits' },
  visitors: { $sum: '$visitors' },
  visits_geo_ab: { $sum: '$visits_geo_ab' },
  visits_geo_bc: { $sum: '$visits_geo_bc' },
  visits_geo_mb: { $sum: '$visits_geo_mb' },
  visits_geo_nb: { $sum: '$visits_geo_nb' },
  visits_geo_nl: { $sum: '$visits_geo_nl' },
  visits_geo_ns: { $sum: '$visits_geo_ns' },
  visits_geo_nt: { $sum: '$visits_geo_nt' },
  visits_geo_nu: { $sum: '$visits_geo_nu' },
  visits_geo_on: { $sum: '$visits_geo_on' },
  visits_geo_outside_canada: { $sum: '$visits_geo_outside_canada' },
  visits_geo_pe: { $sum: '$visits_geo_pe' },
  visits_geo_qc: { $sum: '$visits_geo_qc' },
  visits_geo_sk: { $sum: '$visits_geo_sk' },
  visits_geo_us: { $sum: '$visits_geo_us' },
  visits_geo_yt: { $sum: '$visits_geo_yt' },
  visits_referrer_other: { $sum: '$visits_referrer_other' },
  visits_referrer_searchengine: { $sum: '$visits_referrer_searchengine' },
  visits_referrer_social: { $sum: '$visits_referrer_social' },
  visits_referrer_typed_bookmarked: {
    $sum: '$visits_referrer_typed_bookmarked',
  },
  visits_device_other: { $sum: '$visits_device_other' },
  visits_device_desktop: { $sum: '$visits_device_desktop' },
  visits_device_mobile: { $sum: '$visits_device_mobile' },
  visits_device_tablet: { $sum: '$visits_device_tablet' },
};