export type AADimensionId = |
  'variables/averagepagetime' |
  'variables/browser' |
  'variables/browserheight' |
  'variables/browserheightbucketed' |
  'variables/browsertype' |
  'variables/browserwidth' |
  'variables/browserwidthbucketed' |
  'variables/clickmapaction' |
  'variables/clickmapactiontype' |
  'variables/clickmapcontext' |
  'variables/clickmapcontexttype' |
  'variables/clickmaplink' |
  'variables/clickmaplinkbyregion' |
  'variables/clickmappage' |
  'variables/clickmapregion' |
  'variables/clickmapsourceid' |
  'variables/clickmaptag' |
  'variables/codeversion' |
  'variables/connectiontype' |
  'variables/currency' |
  'variables/currencyfactor' |
  'variables/currencyrate' |
  'variables/custhittimegmt' |
  'variables/customerperspective' |
  'variables/custvisid' |
  'variables/daterangeday' |
  'variables/daterangehour' |
  'variables/daterangeminute' |
  'variables/daterangemonth' |
  'variables/daterangequarter' |
  'variables/daterangeweek' |
  'variables/daterangeyear' |
  'variables/dayssincelastvisit' |
  'variables/duplicatepurchase' |
  'variables/entrylistvariable1' |
  'variables/entrylistvariable1.1' |
  'variables/entrylistvariable1.2' |
  'variables/entrylistvariable2' |
  'variables/entrylistvariable2.1' |
  'variables/entrylistvariable2.2' |
  'variables/entrylistvariable2.3' |
  'variables/entrypage' |
  'variables/entrypageoriginal' |
  'variables/entryprop1' |
  'variables/entryprop11' |
  'variables/entryprop12' |
  'variables/entryprop12.1' |
  'variables/entryprop12.2' |
  'variables/entryprop12.3' |
  'variables/entryprop15' |
  'variables/entryprop16' |
  'variables/entryprop16.1' |
  'variables/entryprop16.2' |
  'variables/entryprop2' |
  'variables/entryprop21' |
  'variables/entryprop21.1' |
  'variables/entryprop21.2' |
  'variables/entryprop21.3' |
  'variables/entryprop22' |
  'variables/entryprop23' |
  'variables/entryprop24' |
  'variables/entryprop25' |
  'variables/entryprop26' |
  'variables/entryprop26.1' |
  'variables/entryprop26.2' |
  'variables/entryprop39' |
  'variables/entryprop4' |
  'variables/entryprop5' |
  'variables/entryprop5.1' |
  'variables/entryprop50' |
  'variables/entryprop6' |
  'variables/entryprop6.1' |
  'variables/entryprop6.2' |
  'variables/entryprop6.3' |
  'variables/entryprop65' |
  'variables/entryprop66' |
  'variables/entryprop66.1' |
  'variables/entryprop7' |
  'variables/entryprop70' |
  'variables/entryprop70.1' |
  'variables/entryprop70.2' |
  'variables/entryprop70.3' |
  'variables/entryprop75' |
  'variables/entryprop75.1' |
  'variables/entryprop75.2' |
  'variables/evar1' |
  'variables/evar10' |
  'variables/evar10.1' |
  'variables/evar10.2' |
  'variables/evar100' |
  'variables/evar100.1' |
  'variables/evar100.2' |
  'variables/evar100.3' |
  'variables/evar11' |
  'variables/evar110' |
  'variables/evar110.1' |
  'variables/evar110.2' |
  'variables/evar110.3' |
  'variables/evar110.4' |
  'variables/evar110.5' |
  'variables/evar110.6' |
  'variables/evar111' |
  'variables/evar111.1' |
  'variables/evar111.2' |
  'variables/evar111.3' |
  'variables/evar111.4' |
  'variables/evar111.5' |
  'variables/evar111.6' |
  'variables/evar112' |
  'variables/evar12' |
  'variables/evar12.1' |
  'variables/evar12.2' |
  'variables/evar12.3' |
  'variables/evar120' |
  'variables/evar120.1' |
  'variables/evar120.2' |
  'variables/evar120.3' |
  'variables/evar120.4' |
  'variables/evar121' |
  'variables/evar121.1' |
  'variables/evar121.2' |
  'variables/evar121.3' |
  'variables/evar121.4' |
  'variables/evar121.5' |
  'variables/evar121.6' |
  'variables/evar122' |
  'variables/evar122.1' |
  'variables/evar122.2' |
  'variables/evar122.3' |
  'variables/evar122.4' |
  'variables/evar123' |
  'variables/evar123.1' |
  'variables/evar123.2' |
  'variables/evar123.3' |
  'variables/evar123.4' |
  'variables/evar123.5' |
  'variables/evar123.6' |
  'variables/evar124' |
  'variables/evar124.1' |
  'variables/evar124.2' |
  'variables/evar124.3' |
  'variables/evar124.4' |
  'variables/evar124.5' |
  'variables/evar124.6' |
  'variables/evar124.7' |
  'variables/evar125' |
  'variables/evar129' |
  'variables/evar13' |
  'variables/evar130' |
  'variables/evar131' |
  'variables/evar132' |
  'variables/evar133' |
  'variables/evar134' |
  'variables/evar135' |
  'variables/evar14' |
  'variables/evar14.1' |
  'variables/evar14.2' |
  'variables/evar14.3' |
  'variables/evar14.4' |
  'variables/evar15' |
  'variables/evar16' |
  'variables/evar16.1' |
  'variables/evar16.2' |
  'variables/evar17' |
  'variables/evar18' |
  'variables/evar18.1' |
  'variables/evar18.2' |
  'variables/evar19' |
  'variables/evar19.1' |
  'variables/evar19.2' |
  'variables/evar2' |
  'variables/evar20' |
  'variables/evar21' |
  'variables/evar21.1' |
  'variables/evar21.2' |
  'variables/evar21.3' |
  'variables/evar22' |
  'variables/evar23' |
  'variables/evar24' |
  'variables/evar25' |
  'variables/evar26' |
  'variables/evar26.1' |
  'variables/evar26.2' |
  'variables/evar27' |
  'variables/evar27.1' |
  'variables/evar27.2' |
  'variables/evar28' |
  'variables/evar29' |
  'variables/evar30' |
  'variables/evar31' |
  'variables/evar32' |
  'variables/evar33' |
  'variables/evar34' |
  'variables/evar35' |
  'variables/evar37' |
  'variables/evar38' |
  'variables/evar39' |
  'variables/evar4' |
  'variables/evar40' |
  'variables/evar41' |
  'variables/evar42' |
  'variables/evar43' |
  'variables/evar44' |
  'variables/evar45' |
  'variables/evar46' |
  'variables/evar5' |
  'variables/evar5.1' |
  'variables/evar50' |
  'variables/evar51' |
  'variables/evar52' |
  'variables/evar53' |
  'variables/evar54' |
  'variables/evar55' |
  'variables/evar57' |
  'variables/evar57.1' |
  'variables/evar59' |
  'variables/evar6' |
  'variables/evar6.1' |
  'variables/evar6.2' |
  'variables/evar6.3' |
  'variables/evar61' |
  'variables/evar61.1' |
  'variables/evar61.2' |
  'variables/evar62' |
  'variables/evar63' |
  'variables/evar65' |
  'variables/evar66' |
  'variables/evar66.1' |
  'variables/evar70' |
  'variables/evar70.1' |
  'variables/evar70.2' |
  'variables/evar70.3' |
  'variables/evar71' |
  'variables/evar71.1' |
  'variables/evar71.2' |
  'variables/evar72' |
  'variables/evar75' |
  'variables/evar75.1' |
  'variables/evar75.2' |
  'variables/evar76' |
  'variables/evar77' |
  'variables/evar77.1' |
  'variables/evar77.2' |
  'variables/evar77.3' |
  'variables/evar78' |
  'variables/evar79' |
  'variables/evar8' |
  'variables/evar80' |
  'variables/evar86' |
  'variables/evar87' |
  'variables/evar88' |
  'variables/evar89' |
  'variables/evar9' |
  'variables/evar9.1' |
  'variables/evar90' |
  'variables/evar90.1' |
  'variables/evar90.2' |
  'variables/evar90.3' |
  'variables/evar90.4' |
  'variables/evar91' |
  'variables/evar91.1' |
  'variables/evar91.2' |
  'variables/evar91.3' |
  'variables/evar91.4' |
  'variables/evar91.5' |
  'variables/evar91.6' |
  'variables/evar91.7' |
  'variables/evar91.8' |
  'variables/evar92' |
  'variables/evar92.1' |
  'variables/evar92.2' |
  'variables/evar92.3' |
  'variables/evar92.4' |
  'variables/evar92.5' |
  'variables/evar92.6' |
  'variables/evar92.7' |
  'variables/evar93' |
  'variables/evar93.1' |
  'variables/evar93.2' |
  'variables/evar93.3' |
  'variables/evar93.4' |
  'variables/evar94' |
  'variables/evar94.1' |
  'variables/evar94.2' |
  'variables/evar94.3' |
  'variables/evar94.4' |
  'variables/evar94.5' |
  'variables/evar94.6' |
  'variables/evar94.7' |
  'variables/evar94.8' |
  'variables/evar95' |
  'variables/evar95.1' |
  'variables/evar95.2' |
  'variables/evar95.3' |
  'variables/evar95.4' |
  'variables/evar95.5' |
  'variables/evar95.6' |
  'variables/evar95.7' |
  'variables/evar96' |
  'variables/evar96.1' |
  'variables/evar96.2' |
  'variables/evar96.3' |
  'variables/evar96.4' |
  'variables/evar96.5' |
  'variables/evar96.6' |
  'variables/evar96.7' |
  'variables/exitlink' |
  'variables/exitlistvariable1' |
  'variables/exitlistvariable1.1' |
  'variables/exitlistvariable1.2' |
  'variables/exitlistvariable2' |
  'variables/exitlistvariable2.1' |
  'variables/exitlistvariable2.2' |
  'variables/exitlistvariable2.3' |
  'variables/exitpage' |
  'variables/exitprop1' |
  'variables/exitprop11' |
  'variables/exitprop12' |
  'variables/exitprop12.1' |
  'variables/exitprop12.2' |
  'variables/exitprop12.3' |
  'variables/exitprop15' |
  'variables/exitprop16' |
  'variables/exitprop16.1' |
  'variables/exitprop16.2' |
  'variables/exitprop2' |
  'variables/exitprop21' |
  'variables/exitprop21.1' |
  'variables/exitprop21.2' |
  'variables/exitprop21.3' |
  'variables/exitprop22' |
  'variables/exitprop23' |
  'variables/exitprop24' |
  'variables/exitprop25' |
  'variables/exitprop26' |
  'variables/exitprop26.1' |
  'variables/exitprop26.2' |
  'variables/exitprop39' |
  'variables/exitprop4' |
  'variables/exitprop5' |
  'variables/exitprop5.1' |
  'variables/exitprop50' |
  'variables/exitprop6' |
  'variables/exitprop6.1' |
  'variables/exitprop6.2' |
  'variables/exitprop6.3' |
  'variables/exitprop65' |
  'variables/exitprop66' |
  'variables/exitprop66.1' |
  'variables/exitprop7' |
  'variables/exitprop70' |
  'variables/exitprop70.1' |
  'variables/exitprop70.2' |
  'variables/exitprop70.3' |
  'variables/exitprop75' |
  'variables/exitprop75.1' |
  'variables/exitprop75.2' |
  'variables/filtereddomain' |
  'variables/geocity' |
  'variables/geocountry' |
  'variables/geolatitude' |
  'variables/geolongitude' |
  'variables/georegion' |
  'variables/geozip' |
  'variables/hitdatetimeoffset' |
  'variables/hitdepth' |
  'variables/hittimegmt' |
  'variables/hittimegmtfirsthit' |
  'variables/hittype' |
  'variables/ipaddress2' |
  'variables/latitude' |
  'variables/listvariable1' |
  'variables/listvariable1.1' |
  'variables/listvariable1.2' |
  'variables/listvariable2' |
  'variables/listvariable2.1' |
  'variables/listvariable2.2' |
  'variables/listvariable2.3' |
  'variables/longitude' |
  'variables/mobilebookmarklength' |
  'variables/mobilecarrier' |
  'variables/mobiledevicename' |
  'variables/mobiledevicenumber' |
  'variables/mobiledevicetype' |
  'variables/mobiledrm' |
  'variables/mobileinformationservices' |
  'variables/mobilejavavm' |
  'variables/mobilemaildecoration' |
  'variables/mobilemanufacturer' |
  'variables/mobilenetprotocols' |
  'variables/mobileos' |
  'variables/mobilepushtotalk' |
  'variables/mobilescreenheight' |
  'variables/mobilescreensize' |
  'variables/mobilescreenwidth' |
  'variables/monitorresolution' |
  'variables/newvisit' |
  'variables/nextpage' |
  'variables/operatingsystem' |
  'variables/operatingsystemgroup' |
  'variables/page' |
  'variables/pageevent' |
  'variables/pageeventmedia' |
  'variables/pageeventvar1' |
  'variables/pageeventvar2' |
  'variables/pageeventvar3' |
  'variables/pagenamenourl' |
  'variables/pagetimeseconds' |
  'variables/pageurl' |
  'variables/pageurlfirsthit' |
  'variables/pageurlvisitstart' |
  'variables/partnerplugins' |
  'variables/pathlength' |
  'variables/preloaded' |
  'variables/previouspage' |
  'variables/prop1' |
  'variables/prop11' |
  'variables/prop12' |
  'variables/prop12.1' |
  'variables/prop12.2' |
  'variables/prop12.3' |
  'variables/prop15' |
  'variables/prop16' |
  'variables/prop16.1' |
  'variables/prop16.2' |
  'variables/prop2' |
  'variables/prop21' |
  'variables/prop21.1' |
  'variables/prop21.2' |
  'variables/prop21.3' |
  'variables/prop22' |
  'variables/prop23' |
  'variables/prop24' |
  'variables/prop25' |
  'variables/prop26' |
  'variables/prop26.1' |
  'variables/prop26.2' |
  'variables/prop39' |
  'variables/prop4' |
  'variables/prop5' |
  'variables/prop5.1' |
  'variables/prop50' |
  'variables/prop6' |
  'variables/prop6.1' |
  'variables/prop6.2' |
  'variables/prop6.3' |
  'variables/prop65' |
  'variables/prop66' |
  'variables/prop66.1' |
  'variables/prop7' |
  'variables/prop70' |
  'variables/prop70.1' |
  'variables/prop70.2' |
  'variables/prop70.3' |
  'variables/prop75' |
  'variables/prop75.1' |
  'variables/prop75.2' |
  'variables/referrer' |
  'variables/referrerfirsthit' |
  'variables/referrertype' |
  'variables/referrertypefirsthit' |
  'variables/referrertypevisit' |
  'variables/referrervisit' |
  'variables/referringdomain' |
  'variables/referringdomainoriginal' |
  'variables/referringdomainvisit' |
  'variables/returnfrequency' |
  'variables/rsid' |
  'variables/searchengine' |
  'variables/searchenginekeywordvisit' |
  'variables/searchenginepagerank' |
  'variables/searchenginevisit' |
  'variables/service' |
  'variables/singlepagevisits' |
  'variables/sitetime' |
  'variables/sslhit' |
  'variables/startnewvisit' |
  'variables/targetraw' |
  'variables/targetraw.4' |
  'variables/targetraw.activity' |
  'variables/targetraw.activityexperience' |
  'variables/targetraw.controlvstargeted' |
  'variables/targetraw.experience' |
  'variables/timepartampm' |
  'variables/timepartdayofmonth' |
  'variables/timepartdayofweek' |
  'variables/timepartdayofyear' |
  'variables/timeparthourofday' |
  'variables/timepartmonthofyear' |
  'variables/timepartquarterofyear' |
  'variables/timepartweekdayweekend' |
  'variables/timeprior' |
  'variables/timespent' |
  'variables/timezone' |
  'variables/timezonevalue' |
  'variables/tnt' |
  'variables/tntaction' |
  'variables/topleveldomain' |
  'variables/transactionid' |
  'variables/truncatedhit' |
  'variables/uacolor' |
  'variables/uaoperatingsystem' |
  'variables/uapixels' |
  'variables/useragent' |
  'variables/userid' |
  'variables/vanewengagement' |
  'variables/visidnew' |
  'variables/visidtype' |
  'variables/visitnumber' |
  'variables/visitpagenum' |
  'variables/visitstarttimegmt' |
  ''
